### ISSUE TITLE
Critical issue In new gradle when I switch second category and again first.

### ISSUE THREAD

**Issue by mabhim99** [iamvaliyev/MultiTabMenu#2]
when I switch the second category and again the first category then first subcategory change by the second subcategory.

**Comment by brkckr** [comment]
When I touch the any category, the sub-categories don't change. Also, if the categories change quickly, the sub-categories are getting confused.

**Comment by iamvaliyev** [comment]
@mabhim99 , @brkckr I fixed this problem. Pull latest version and use:
compile 'com.github.iamvaliyev:MultiTabMenu:v1.0.1'
Happy Coding! 😃
