### ISSUE TITLE
Gradle not sync

### ISSUE THREAD

**Issue by abhi9** [iamvaliyev/MultiTabMenu#2]
I have add dependency compile 'io.github.iamvaliyev:library:1.0' even I have add repo mavenCentral() but its create problem Error:(32, 13) Failed to resolve: io.github.iamvaliyev:library:1.0
<a href="openFile:/Downloads/googleads-mobile-android-examples-master/advanced/gkenglishfinal/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by iamvaliyev** [comment]
Problem resolved: 

repositories{
    maven { url 'https://jitpack.io' }
}

dependencies{
    compile 'com.github.iamvaliyev:MultiTabMenu:1.0.0'
}

**Comment by abhi9** [comment]
Thanks its working
